name: "Tag version when version file changes"

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - "speechbrain/version.txt"

jobs:
  tag-version:
    name: "Tag version"
    runs-on: "ubuntu-latest"
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v1
        with:
          ref: main
      - name: "Tag version"
        run: |
          git tag v`cat speechbrain/version.txt`
          git push --tag

