name: "Tag version when version file changes"

on:  # yamllint disable-line rule:truthy
  push:
    branch:
      - "main"
    paths:
      - "speechbrain/version.txt"

jobs:
  pre-release:
    name: "Tag version"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: "Tag version"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag v`cat speechbrain/version.txt`
          git push --tag

